server:
  port: 8088



management:
  endpoint:
    health:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true
    health:
      show-details: always
hystrix:
  metrics:
    enabled: true
  dashboard:
    proxy-stream-allow-list: "*"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: film-controller
          uri: lb://FILM-CONTROLLER
          predicates:
            - Path=/film-controller/**

        - id: controller
          uri: lb://CONTROLLER
          predicates:
            - Path=/controller/**
#          filters:
#            - name: Pre
#              args:
#                name: apply
#                fallbackUri: forward:/fb/film
#            - RewritePath=/(?<segment>/?.*), $\{segment}

#        - id: circuitbreaker_route
#          uri: lb://backing-service:8088
#          predicates:
#            - Path=/consumingServiceEndpoint
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/inCaseOfFailureUseThis
#            - RewritePath=/consumingServiceEndpoint, /backingServiceEndpoint

