version: '3.7'
services:
  elastic-search:
    image: elasticsearch:${ELASTIC_VERSION:-latest}
    container_name: cvl_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
#    networks:
#      - ${GLOBAL_NETWORK:-elastic}
  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: cvl_kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
#    networks:
#      - ${GLOBAL_NETWORK:-elastic}
  logstash:
    image: logstash:${ELASTIC_VERSION}
    container_name: cvl_logstash
    restart: always
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true
#    networks:
#      - ${GLOBAL_NETWORK:-elastic}
