version: '3.7'
services:
#  keycloak-authorization-server:
#    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
#    hostname: keycloak-server
#    ports:
#      - "9091:9091"
#    environment:
#      - "KEYCLOAK_USER=admin"
#      - "KEYCLOAK_PASSWORD=admin"
#      - "JAVA_OPTS=-Djboss.http.port=9091"
#      - "DB_VENDOR=POSTGRES"
#      - "DB_ADDR=host.docker.internal"
#      - "DB_DATABASE=keycloak"
#      - "DB_USER=keycloak"
#      - "DB_SCHEMA=keycloak"
#      - "DB_PASSWORD=keycloak"

  config-server:
    image: ${GROUP_ID}/config.server:${SERVICE_VERSION:-latest}
    ports:
      - "5100:5100"
      - "8888:8888"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5100 -Xms128m -Xmx256m"
      - "SERVER_PORT=8888"

  gateway-server:
    image: ${GROUP_ID}/gateway.server:${SERVICE_VERSION:-latest}
    ports:
      - "5101:5101"
      - "8088:8088"
    depends_on:
      - eureka-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5101 -Xms128m -Xmx256m"
      - "SERVER_PORT=8088"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"

  eureka-server:
    image: ${GROUP_ID}/eureka.server:${SERVICE_VERSION:-latest}
    ports:
      - "5102:5102"
      - "8761:8761"
    volumes:
      - "./docker-logs:/workspace/eureka-server/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5102 -Xms128m -Xmx256m"
      - "SERVER_PORT=8761"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"


  film-controller:
    image: ${GROUP_ID}/film.controller:${SERVICE_VERSION:-latest}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/film-controller/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
#      - keycloak-authorization-server
      - kafka-broker-1
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka-broker-1:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"
      - "KEYCLOAK_AUTH-SERVER-URL=http://localhost:9091/auth/"
#      - "KEYCLOAK_AUTH-SERVER-URL=http://host.docker.internal:9091/auth/"
#      - "KEYCLOAK_AUTH-SERVER-URL=http://keycloak-authorization-server:9091/auth/"

  film-process:
    image: ${GROUP_ID}/film.process:${SERVICE_VERSION:-latest}
    ports:
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/film-process/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - kafka-broker-1
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka-broker-1:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"

  controller:
    image: ${GROUP_ID}/controller:${SERVICE_VERSION:-latest}
    ports:
      - "5007:5007"
    volumes:
      - "./docker-logs:/workspace/controller/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - kafka-broker-2
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka-broker-2:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"

  favourite-process:
    image: ${GROUP_ID}/favourite-process:${SERVICE_VERSION:-latest}
    ports:
      - "5008:5008"
    volumes:
      - "./docker-logs:/workspace/favourite-process/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - kafka-broker-2
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka-broker-2:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"

  rate-process:
    image: ${GROUP_ID}/rate-process:${SERVICE_VERSION:-latest}
    ports:
      - "5009:5009"
    volumes:
      - "./docker-logs:/workspace/rate-process/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - kafka-broker-2
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka-broker-2:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"

  watched-content-process:
    image: ${GROUP_ID}/watched-content-process:${SERVICE_VERSION:-latest}
    ports:
      - "5010:5010"
    volumes:
      - "./docker-logs:/workspace/watched-content-process/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    entrypoint: [ "check-config-server-started.sh" ]
    depends_on:
      - config-server
      - kafka-broker-2
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5010 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/netflix"
      - "SPRING_ZIPKIN_BASE-URL=http://host.docker.internal:9411/"
      - "SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka-broker-2:9092"
      - "EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://eureka-server:8761/eureka/"


